### ISSUE TITLE
Keyboard row/col codes are not necessarily accurate

### ISSUE THREAD

**Issue by Restioson** [flower-os/flower#37]
Currently, the bottom row of the keymap is not necessarily accurate for everyone. For instance, we define a `RIGHT_WIN` and `LEFT_WIN` -- on my keyboard, I only have the left win key, and the right one is a context-menu button, and some people may not have a win key at all! We should address this somehow -- perhaps by having aliases for these positions. Thoughts?

**Comment by gegy1000** [comment]
Right. Maybe we should have key codes based on row/column for alphanumeric characters, but arbitrary codes for others? We can do this for alphanumeric because we are guaranteed they will be in the same positions. (or, at least, relative to the rest of the keys)

**Comment by Restioson** [comment]
We could make these key codes arbitrary but semantic meaning can be applied to them via a keymap thing? We can think more about this when it's moved to userspace.

**Comment by gegy1000** [comment]
These keycodes are essentially already arbitrary. I could be misremembering, but I don't think their IDs are relevant?

**Comment by Restioson** [comment]
Let's just note that they are arbitrary and the close the issue when that's done.

**Comment by Restioson** [comment]
Closing now -- please remember to note that it is only loosely based on row/cols @gegy1000.
