### ISSUE TITLE
Meltdown and Spectre

### ISSUE THREAD

**Issue by Restioson** [flower-os/flower#70]
Are we going to try to mitigate meltdown and spectre? In what ways? I think it is important to discuss whether we want to or need to based on that flower is a hobby OS in any case, but I would still like it to be secure. It also might be too much trouble for what it's worth, especially considering that it will most likely be fixed in future chip releases. 

Thoughts?

**Comment by gegy1000** [comment]
For a hobby OS, I don't think it is worth it. Especially at this stage, where we barely have working user input. This might be something that we should bring up again in the future, though for now we can ignore it.

**Comment by Restioson** [comment]
Fair. It just doesn't sit right with me completely disregarding a security flaw.

**Comment by Restioson** [comment]
For now let's just not.
